"""
Derives default land value rates (currency per m²) for Lilongwe's Areas and
Sectors from the 2011 Quinquennial Valuation Roll extract, and writes them as
a JavaScript global the app loads as its default schedule.

The 2011 roll states land value and parcel area (hectares) for each plot.
The Area is the number before the first "/" in the plot number ("46/1/232"
is in Area 46; "46/1" is its Sector where the sector layer has one).

IMPORTANT: these are 2011 capital values in Malawi Kwacha. They are a
starting point for the registered valuer to review and bring to the current
valuation date and basis, not current rates.

Run from the repository root:  python3 data/build_land_rates.py
Writes: data/land_rates_default.js
"""
import csv
import json
import os
import re
import sqlite3
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
QVR = os.path.join(ROOT, "QVR 2011 COMBINED-ADAMS5_extract.csv")
GPKG = os.path.join(ROOT, "lilongwe_valuation_tool_gis_files.gpkg")
MIN_N = 5


def num(s):
    s = (s or "").replace(",", "").strip()
    try:
        return float(s)
    except ValueError:
        return None


def col(row, name):
    """Column names in the extract carry stray spaces; match on the trimmed name."""
    for k, v in row.items():
        if k is not None and re.sub(r"\s+", " ", k).strip().lower() == name:
            return v
    return None


def plot_keys(plot):
    """Return (area_id, sector_key) from a plot number, or (None, None)."""
    parts = [p.strip() for p in str(plot).split("/")]
    if len(parts) < 2 or not re.fullmatch(r"\d+", parts[0]):
        return None, None
    area = int(parts[0])
    if len(parts) >= 3 and re.fullmatch(r"\d+", parts[1]):
        return area, "%d/%s" % (area, parts[1])
    return area, str(area)


def summarise(rates):
    rates = sorted(rates)
    q = lambda p: rates[int(round(p * (len(rates) - 1)))]
    return {"rate": round(statistics.median(rates)), "n": len(rates), "p25": round(q(0.25)), "p75": round(q(0.75))}


def main():
    db = sqlite3.connect(GPKG)
    area_ids = {r[0] for r in db.execute("select Area_ID from area_boundaries where Area_ID is not null and Area_ID != 0")}
    sector_keys = {r[0] for r in db.execute("select Area_Secto from sector_boundaries where Area_Secto is not null")}

    by_area, by_sector, all_rates = defaultdict(list), defaultdict(list), []
    skipped = {"blank": 0, "unparseable": 0, "no_area_or_value": 0, "area_not_in_map": 0}
    with open(QVR, encoding="utf-8-sig", errors="replace", newline="") as fh:
        for row in csv.DictReader(fh):
            plot = (col(row, "plot no.") or "").strip()
            if not plot:
                skipped["blank"] += 1
                continue
            area, sector = plot_keys(plot)
            if area is None:
                skipped["unparseable"] += 1
                continue
            ha = num(col(row, "area (ha)"))
            land = num(col(row, "land value"))
            if not ha or not land or ha <= 0 or land <= 0:
                skipped["no_area_or_value"] += 1
                continue
            if area not in area_ids:
                skipped["area_not_in_map"] += 1
                continue
            rate = land / (ha * 10000.0)
            by_area[area].append(rate)
            all_rates.append(rate)
            if sector in sector_keys:
                by_sector[sector].append(rate)

    out = {
        "source": "Lilongwe City Council Quinquennial Valuation Roll 2011 (COMBINED-ADAMS5 extract)",
        "basis": "capital value, 2011, Malawi Kwacha per square metre of parcel",
        "method": "median of land value / parcel area over plots in each Area or Sector; Areas/Sectors with fewer than %d plots omitted" % MIN_N,
        "cityMedian": round(statistics.median(all_rates)),
        "plotsUsed": len(all_rates),
        "areas": {str(a): summarise(v) for a, v in sorted(by_area.items()) if len(v) >= MIN_N},
        "sectors": {k: summarise(v) for k, v in sorted(by_sector.items()) if len(v) >= MIN_N},
    }
    path = os.path.join(HERE, "land_rates_default.js")
    with open(path, "w") as fh:
        fh.write("// Generated by data/build_land_rates.py from the QVR 2011 extract. 2011 capital values; review before use.\n")
        fh.write("window.LAND_RATES_DEFAULT = ")
        json.dump(out, fh, indent=1)
        fh.write(";\n")
    print("wrote", path)
    print("plots used", len(all_rates), "skipped", skipped)
    print("areas with rates", len(out["areas"]), "sectors with rates", len(out["sectors"]), "city median", out["cityMedian"])
    for a in ("3", "10", "25", "49"):
        print("  Area", a, out["areas"].get(a))


if __name__ == "__main__":
    main()
