"""
Converts the Area and Sector boundary layers of lilongwe_valuation_tool_gis_files.gpkg
into GeoJSON embedded in JavaScript globals, so the app can load them from a
plain folder (file://) as well as from a web server.

Pure Python: reads the GeoPackage with sqlite3 and decodes the GeoPackage
binary geometry header plus WKB MultiPolygon/Polygon by hand.

Run from the repository root:  python3 data/gpkg_to_geojson.py
Writes: data/lilongwe_areas.js, data/lilongwe_sectors.js
"""
import json
import os
import sqlite3
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GPKG = os.path.join(ROOT, "lilongwe_valuation_tool_gis_files.gpkg")
PRECISION = 6


def decode_geometry(blob):
    """GeoPackage binary -> GeoJSON geometry (Polygon or MultiPolygon)."""
    if blob is None:
        return None
    flags = blob[3]
    envelope_code = (flags >> 1) & 7
    envelope_len = {0: 0, 1: 32, 2: 48, 3: 48, 4: 64}[envelope_code]
    wkb = blob[8 + envelope_len:]
    pos = 0

    def read(fmt):
        nonlocal pos
        values = struct.unpack_from(fmt, wkb, pos)
        pos += struct.calcsize(fmt)
        return values

    def ring(endian):
        (n,) = read(endian + "I")
        pts = []
        for _ in range(n):
            x, y = read(endian + "dd")
            pts.append([round(x, PRECISION), round(y, PRECISION)])
        return pts

    def geometry():
        nonlocal pos
        endian = "<" if wkb[pos] == 1 else ">"
        pos += 1
        (gtype,) = read(endian + "I")
        gtype = gtype % 1000  # strip Z/M flags
        if gtype == 3:
            (nrings,) = read(endian + "I")
            return {"type": "Polygon", "coordinates": [ring(endian) for _ in range(nrings)]}
        if gtype == 6:
            (npolys,) = read(endian + "I")
            polys = [geometry()["coordinates"] for _ in range(npolys)]
            return {"type": "MultiPolygon", "coordinates": polys}
        raise ValueError("unsupported geometry type %d" % gtype)

    return geometry()


def export_layer(db, table, keep, out_name, global_name, key_fn):
    cols = [c[1] for c in db.execute("pragma table_info('%s')" % table)]
    attrs = [c for c in cols if c in keep]
    features = []
    for row in db.execute("select geom, %s from '%s'" % (", ".join(attrs), table)):
        geom = decode_geometry(row[0])
        props = dict(zip(attrs, row[1:]))
        if geom is None or not key_fn(props):
            continue
        features.append({"type": "Feature", "properties": props, "geometry": geom})
    fc = {"type": "FeatureCollection", "features": features}
    path = os.path.join(HERE, out_name)
    with open(path, "w") as fh:
        fh.write("// Generated by data/gpkg_to_geojson.py from lilongwe_valuation_tool_gis_files.gpkg. Do not edit.\n")
        fh.write("window.%s = " % global_name)
        json.dump(fc, fh, separators=(",", ":"))
        fh.write(";\n")
    print("wrote", path, len(features), "features,", os.path.getsize(path) // 1024, "KB")


def main():
    db = sqlite3.connect(GPKG)
    export_layer(db, "area_boundaries", ["Area_ID", "Label_Area", "Land_Use"], "lilongwe_areas.js", "LILONGWE_AREAS",
                 lambda p: p.get("Area_ID") not in (None, 0))
    export_layer(db, "sector_boundaries", ["Area_ID", "Area_Secto", "Sector", "Land_Use", "Ownership"], "lilongwe_sectors.js", "LILONGWE_SECTORS",
                 lambda p: p.get("Area_Secto"))


if __name__ == "__main__":
    main()
